name: main-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Super-Linter
      uses: super-linter/super-linter@02a1172d274f021e4c70f66e23f1085eadd1064b
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - name: Install dependencies
      run: go get .
    - name: Build
      run: go build -v ./...